name: Publish Signature analysis image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/signature-analysis

jobs:
  build-and-push:
    name: Build Signature analysis container
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log into Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Get current date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./containers/signature_analysis
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ IMAGE_NAME }}:${{ DATE }}
            ${{ env.REGISTRY }}/${{ IMAGE_NAME }}:latest
          build-args: |
            VERSION=${{ DATE }}
